version: '1.0'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    # mongo_data:/data/db
      - /Users/chanunchidadithakumarn/Documents/ISP/todo101:/data/db

  todo-backend:
    build: ./backend
    ports:
      - "15000:15000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todo
    depends_on:
      - mongo

  todo-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
